// user
export const USER_INIT = 'USER_INIT'

// aside
export const ASIDE_SET_ACTIVE_MENU_KEY = 'ASIDE_SET_ACTIVE_MENU_KEY'

// agentWorkflow
export const AGENTWORKFLOW_CONCAT_LIST = 'AGENTWORKFLOW_CONCAT_LIST'
export const AGENTWORKFLOW_DELETE_BADGE_BY_ID = 'AGENTWORKFLOW_DELETE_BADGE_BY_ID'